# Generated by Django 3.2.9 on 2022-01-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffPanel', '0003_adminorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
