# Generated by Django 3.1.7 on 2021-07-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaDelivery', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
