# Generated by Django 3.2.9 on 2022-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderHandeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_id',
            field=models.CharField(default='', max_length=7, null=True),
        ),
    ]
